package com.preparatorio.hackathon.agendamento_pagamentos.exceptions;

public class UsuariosNaoEncontradosException extends RuntimeException {
    public UsuariosNaoEncontradosException(String message) {
        super(message);
    }
}
